// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// Robust_filter
std::list< std::list <  std::list < Eigen::MatrixXd > > > Robust_filter(const std::list<std::list<Eigen::MatrixXd> >& Y_expanded, const std::list<Eigen::MatrixXd>& C_list, const std::list<Eigen::MatrixXd>& Sigma_Add_list, const std::list<Eigen::MatrixXd>& Sigma_Inn_Contribution, const Eigen::MatrixXd& A, const Eigen::MatrixXd& Sigma_Inn, const Eigen::MatrixXd& Sigma_Add, const double& s, const int& Num_Descendents, const int& Num_Particles, const std::list<std::vector<int> >& to_sample, const std::vector<int>& Number_of_resamples, const std::vector<double>& sigma_tilde, const std::vector<double>& sigma_hat, const Eigen::MatrixXd& mu_0, const Eigen::MatrixXd& Sigma_0, const int& horizon, const std::vector <double>& prob_inn, const std::vector <double>& prob_add, int Particle_Number, const std::list<Eigen::MatrixXd>& Y_Full_list);
RcppExport SEXP _Robkf_Robust_filter(SEXP Y_expandedSEXP, SEXP C_listSEXP, SEXP Sigma_Add_listSEXP, SEXP Sigma_Inn_ContributionSEXP, SEXP ASEXP, SEXP Sigma_InnSEXP, SEXP Sigma_AddSEXP, SEXP sSEXP, SEXP Num_DescendentsSEXP, SEXP Num_ParticlesSEXP, SEXP to_sampleSEXP, SEXP Number_of_resamplesSEXP, SEXP sigma_tildeSEXP, SEXP sigma_hatSEXP, SEXP mu_0SEXP, SEXP Sigma_0SEXP, SEXP horizonSEXP, SEXP prob_innSEXP, SEXP prob_addSEXP, SEXP Particle_NumberSEXP, SEXP Y_Full_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::list<std::list<Eigen::MatrixXd> >& >::type Y_expanded(Y_expandedSEXP);
    Rcpp::traits::input_parameter< const std::list<Eigen::MatrixXd>& >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< const std::list<Eigen::MatrixXd>& >::type Sigma_Add_list(Sigma_Add_listSEXP);
    Rcpp::traits::input_parameter< const std::list<Eigen::MatrixXd>& >::type Sigma_Inn_Contribution(Sigma_Inn_ContributionSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sigma_Inn(Sigma_InnSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sigma_Add(Sigma_AddSEXP);
    Rcpp::traits::input_parameter< const double& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int& >::type Num_Descendents(Num_DescendentsSEXP);
    Rcpp::traits::input_parameter< const int& >::type Num_Particles(Num_ParticlesSEXP);
    Rcpp::traits::input_parameter< const std::list<std::vector<int> >& >::type to_sample(to_sampleSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Number_of_resamples(Number_of_resamplesSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type sigma_tilde(sigma_tildeSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type sigma_hat(sigma_hatSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type mu_0(mu_0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sigma_0(Sigma_0SEXP);
    Rcpp::traits::input_parameter< const int& >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< const std::vector <double>& >::type prob_inn(prob_innSEXP);
    Rcpp::traits::input_parameter< const std::vector <double>& >::type prob_add(prob_addSEXP);
    Rcpp::traits::input_parameter< int >::type Particle_Number(Particle_NumberSEXP);
    Rcpp::traits::input_parameter< const std::list<Eigen::MatrixXd>& >::type Y_Full_list(Y_Full_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Robust_filter(Y_expanded, C_list, Sigma_Add_list, Sigma_Inn_Contribution, A, Sigma_Inn, Sigma_Add, s, Num_Descendents, Num_Particles, to_sample, Number_of_resamples, sigma_tilde, sigma_hat, mu_0, Sigma_0, horizon, prob_inn, prob_add, Particle_Number, Y_Full_list));
    return rcpp_result_gen;
END_RCPP
}
// Sigma_Limit
Eigen::MatrixXd Sigma_Limit(Eigen::MatrixXd Sigma0, Eigen::MatrixXd C, Eigen::MatrixXd A, Eigen::MatrixXd Sigma_Inn, Eigen::MatrixXd Sigma_Add, double epsilon);
RcppExport SEXP _Robkf_Sigma_Limit(SEXP Sigma0SEXP, SEXP CSEXP, SEXP ASEXP, SEXP Sigma_InnSEXP, SEXP Sigma_AddSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type C(CSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Sigma_Inn(Sigma_InnSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Sigma_Add(Sigma_AddSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigma_Limit(Sigma0, C, A, Sigma_Inn, Sigma_Add, epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Robkf_Robust_filter", (DL_FUNC) &_Robkf_Robust_filter, 21},
    {"_Robkf_Sigma_Limit", (DL_FUNC) &_Robkf_Sigma_Limit, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_Robkf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
